paths:
  top2vec: "models/top2vec/top2vecmodel_220504"
  primitives: "data/primitives_220503/primitives_corrected_daily.ndjson"
  outdir: 'models/221125_test_run/'

filter:
  min_year: 1500
  max_year: 1520
  min_nchar: 50
  max_nchar: 5000

representation:
  softmax: True
  export_vec: True
  export_docsim: True

prototypes:
  find_prototypes: True
  resolution: 'day'
  doc_rank: 0

novelty:
  windows: [1, 5, 10]